# Generated by Django 4.2.20 on 2025-03-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_notification_property_image_property_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='name',
            field=models.CharField(default='Unnamed Property', max_length=255),
        ),
    ]
