# Generated by Django 4.2.20 on 2025-03-28 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_builderseller_rentedseller_retailerseller_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='status',
        ),
    ]
