# Generated by Django 4.2.20 on 2025-03-28 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_portfolio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='user',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='buyer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inquiry',
            name='contact_info',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
