# Generated by Django 4.2.20 on 2025-03-30 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_inquiry_user_inquiry_buyer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='buyer_type',
            field=models.CharField(choices=[('retailer_buyer', 'Retailer Buyer'), ('investor_buyer', 'Investor Buyer'), ('rented_buyer', 'Rented Buyer')], default='retailer_buyer', max_length=20),
        ),
    ]
