# Generated by Django 4.2.19 on 2025-02-27 08:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('property', '0002_user_profile_transaction_portfolio_notification_cart_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='save_property',
            new_name='SaveProperty',
        ),
        migrations.RenameModel(
            old_name='User_profile',
            new_name='UserProfile',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='quntity',
            new_name='quantity',
        ),
    ]
