# Generated by Django 4.2.19 on 2025-03-01 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_rename_save_property_saveproperty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(upload_to='property_images/'),
        ),
    ]
